#!/command/with-contenv bash
# shellcheck shell=bash

set -e

. /usr/bin/common.sh

log_info 'Starting NPM Improved control plane ...'
exec s6-setuidgid "$PUID:$PGID" /usr/local/bin/npm-improved-control-plane
